package dk.aau.claaudia.openstackgateway.models

/**
 * Openstack stack status enum
 * Based on https://github.com/openstack/heat/blob/968969b99cf9c1cfcde4f5c5345f7bcbd4e8db08/heat/engine/stack.py#L105
 */
enum class StackStatus() {
    CREATE_COMPLETE,
    CREATE_IN_PROGRESS,
    CREATE_FAILED,
    DELETE_COMPLETE,
    DELETE_FAILED,
    DELETE_IN_PROGRESS,
    UPDATE_COMPLETE,
    UPDATE_IN_PROGRESS,
    UPDATE_FAILED,
    ROLLBACK_COMPLETE,
    ROLLBACK_FAILED,
    ROLLBACK_IN_PROGRESS,
    SUSPEND_COMPLETE,
    SUSPEND_FAILED,
    SUSPEND_IN_PROGRESS,
    RESUME_COMPLETE,
    RESUME_IN_PROGRESS,
    RESUME_FAILED,
    ADOPT_COMPLETE,
    ADOPT_IN_PROGRESS,
    ADOPT_FAILED,
    SNAPSHOT_COMPLETE,
    SNAPSHOT_IN_PROGRESS,
    SNAPSHOT_FAILED,
    CHECK_COMPLETE,
    CHECK_IN_PROGRESS,
    CHECK_FAILED,
    RESTORE_COMPLETE,
    RESTORE_IN_PROGRESS,
    RESTORE_FAILED
}
