#Insane amounts of logging
#logging:
#  level:
#    org:
#      springframework: DEBUG

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: trace

